# inventory.ini — Tells Ansible where your server is
#
# CONCEPT: An inventory file lists the servers Ansible manages.
# You can have groups of servers (web, db, cache).
# We only have one server so it is simple.
#
# ansible_host       = the IP address to connect to
# ansible_user       = which Linux user to SSH as
#                      OCI Ubuntu images use 'ubuntu' by default
# ansible_ssh_private_key_file = which SSH key to use

[portfolio]
portfolio-vm ansible_host=145.241.215.190 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/oracle_vm_key

[portfolio:vars]
ansible_python_interpreter=/usr/bin/python3
# Tells Ansible to use Python 3 on the remote server